version: '3'
services:
  spring-server:
    build: ""
    depends_on:
          - db-postgres
    ports:
      - "8000:8080"
    container_name: spring-server
    command: ["/wait-for-it.sh", "db-postgres:5432", "--strict", "--", "java", "-jar", "/app.jar"]
  db-postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: app-database
    ports:
      - "5432:5432"
    container_name: db-postgres
