version: '3'
services:
  screening-server:
    build: ./screening-server
    depends_on:
      - postgres
    ports:
      - "8000:8080"
    container_name: spring-server
    volumes:
      - ${PROJECT_PATH}/screening-server/src/main/resources/wait-for-it:/wait-for-it
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: app-database
    ports:
      - "5432:5432"
    container_name: db-postgres
  flyway:
    build: ./flyway
    volumes:
      - ${PROJECT_PATH}/flyway/sql:/flyway/sql
      - ${PROJECT_PATH}/screening-server/src/main/resources/wait-for-it:/wait-for-it
      - ${PROJECT_PATH}/flyway/conf:/flyway/conf
    depends_on:
      - postgres
    container_name: flyway
    tty: true
