CREATE TABLE SCREENING (
    id BIGINT NOT NULL PRIMARY KEY,
    start_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    duration TIME WITHOUT TIME ZONE NOT NULL,
    movie VARCHAR(50) NOT NULL,
    cinema VARCHAR(50) NOT NULL
);

CREATE SEQUENCE "screening-seq" START 1;